### ISSUE TITLE
before_tests not passing args anymore

### ISSUE THREAD

**Issue by BernsteinA** [testem/testem#1007]
New since pr #998
Logs to follow.

**Comment by BernsteinA** [comment]
```
info Test'em starting.. 
info Seeking for config file... 
info Starting ci 
info Starting server 
info JSDom 
info Waiting for tests. 
info Start triggered test run. 
info Running tests... 
info executing: npm run build:test 
info spawning: npm - [ 'run', 'build:test' ] 
WARN before_tests closed 1
ERR! before_tests error Error: Non-zero exit code: 1
ERR! before_tests error Hook: before_tests
ERR! before_tests error Stdout:
ERR! before_tests error 
ERR! before_tests error Usage: npm <command>
ERR! before_tests error 
ERR! before_tests error where <command> is one of:
ERR! before_tests error     access, adduser, bin, bugs, c, cache, completion, config,
ERR! before_tests error     ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
ERR! before_tests error     help, help-search, i, init, install, install-test, it, link,
ERR! before_tests error     list, ln, login, logout, ls, outdated, owner, pack, ping,
ERR! before_tests error     prefix, prune, publish, rb, rebuild, repo, restart, root,
ERR! before_tests error     run, run-script, s, se, search, set, shrinkwrap, star,
ERR! before_tests error     stars, start, stop, t, tag, team, test, tst, un, uninstall,
ERR! before_tests error     unpublish, unstar, up, update, v, version, view, whoami
ERR! before_tests error 
ERR! before_tests error npm <cmd> -h     quick help on <cmd>
ERR! before_tests error npm -l           display full usage info
ERR! before_tests error npm help <term>  search for help on <term>
ERR! before_tests error npm help npm     involved overview
ERR! before_tests error 
ERR! before_tests error Specify configs in the ini-formatted file:
ERR! before_tests error     /home/ubuntu/.npmrc
ERR! before_tests error or on the command line via: npm <command> --key value
ERR! before_tests error Config info can be viewed via: npm help config
ERR! before_tests error 
ERR! before_tests error npm@3.10.8 /opt/circleci/nodejs/v7.0.0/lib/node_modules/npm
ERR! before_tests error 
ERR! before_tests error Stderr:
ERR! before_tests error 
ERR! before_tests error     at createError (/home/ubuntu/thornwood-heights/node_modules/testem/lib/hook_runner.js:149:10)
ERR! before_tests error     at ProcessCtl.<anonymous> (/home/ubuntu/thornwood-heights/node_modules/testem/lib/hook_runner.js:96:25)
ERR! before_tests error     at emitThree (events.js:116:13)
ERR! before_tests error     at ProcessCtl.emit (events.js:194:7)
ERR! before_tests error     at ProcessCtl.onClose (/home/ubuntu/thornwood-heights/node_modules/testem/lib/process-ctl.js:189:8)
ERR! before_tests error     at emitTwo (events.js:106:13)
ERR! before_tests error     at ChildProcess.emit (events.js:191:7)
ERR! before_tests error     at maybeClose (internal/child_process.js:877:16)
ERR! before_tests error     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
ERR! before_tests error  Error: Non-zero exit code: 1
ERR! before_tests error Hook: before_tests
ERR! before_tests error Stdout:
ERR! before_tests error 
ERR! before_tests error Usage: npm <command>
ERR! before_tests error 
ERR! before_tests error where <command> is one of:
ERR! before_tests error     access, adduser, bin, bugs, c, cache, completion, config,
ERR! before_tests error     ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
ERR! before_tests error     help, help-search, i, init, install, install-test, it, link,
ERR! before_tests error     list, ln, login, logout, ls, outdated, owner, pack, ping,
ERR! before_tests error     prefix, prune, publish, rb, rebuild, repo, restart, root,
ERR! before_tests error     run, run-script, s, se, search, set, shrinkwrap, star,
ERR! before_tests error     stars, start, stop, t, tag, team, test, tst, un, uninstall,
ERR! before_tests error     unpublish, unstar, up, update, v, version, view, whoami
ERR! before_tests error 
ERR! before_tests error npm <cmd> -h     quick help on <cmd>
ERR! before_tests error npm -l           display full usage info
ERR! before_tests error npm help <term>  search for help on <term>
ERR! before_tests error npm help npm     involved overview
ERR! before_tests error 
ERR! before_tests error Specify configs in the ini-formatted file:
ERR! before_tests error     /home/ubuntu/.npmrc
ERR! before_tests error or on the command line via: npm <command> --key value
ERR! before_tests error Config info can be viewed via: npm help config
ERR! before_tests error 
ERR! before_tests error npm@3.10.8 /opt/circleci/nodejs/v7.0.0/lib/node_modules/npm
ERR! before_tests error 
ERR! before_tests error Stderr:
ERR! before_tests error 
ERR! before_tests error     at createError (/home/ubuntu/thornwood-heights/node_modules/testem/lib/hook_runner.js:149:10)
ERR! before_tests error     at ProcessCtl.<anonymous> (/home/ubuntu/thornwood-heights/node_modules/testem/lib/hook_runner.js:96:25)
ERR! before_tests error     at emitThree (events.js:116:13)
ERR! before_tests error     at ProcessCtl.emit (events.js:194:7)
ERR! before_tests error     at ProcessCtl.onClose (/home/ubuntu/thornwood-heights/node_modules/testem/lib/process-ctl.js:189:8)
ERR! before_tests error     at emitTwo (events.js:106:13)
ERR! before_tests error     at ChildProcess.emit (events.js:191:7)
ERR! before_tests error     at maybeClose (internal/child_process.js:877:16)
ERR! before_tests error     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
info Process JSDom already killed. 
```

**Comment by johanneswuerbach** [comment]
Could you post your testem config?

**Comment by BernsteinA** [comment]
```
{
    "framework": "tap",
    "launchers": {
        "JSDom": {
            "command": "node -r jsdom-global/register ./temp/test_bundle.js",
            "protocol": "tap"
        }
    },
    "src_files": [
      "test/*.js",
      "test/*.jsx"
    ],
    "serve_files": [
      "temp/test_bundle.js"
    ],
    "before_tests": "npm run build:test",
    "launch_in_ci": ["Chrome"],
    "launch_in_dev": ["JSDom", "Chrome", "Firefox", "Safari"],
    "reporter": "xunit",
    "xunit_intermediate_output": true,
    "report_file": "testem.xml"
}
```

**Comment by johanneswuerbach** [comment]
Is this error happing only in Node 7 or also in older versions? Testem is currently no tested against 7, but should work.

**Comment by johanneswuerbach** [comment]
Looks like Node 7 was really the issue, submitted a fix to an upstream dependency. https://github.com/IndigoUnited/node-cross-spawn/pull/48

**Comment by BernsteinA** [comment]
Nice. Thanks

**Comment by johanneswuerbach** [comment]
The upstream issue has been fixed and it should work once you reinstall testem or just cross-spawn

**Comment by tylerball** [comment]
I'm also experiencing this on node v5.7.0 with testem 1.14.2. Here's my testem.json:

```
{
  "framework": "mocha",
  "before_tests": "npm run-script test-build",
  "after_tests": "npm run-script test-cleanup",
  "src_files": [
    "tmp/test.js"
  ],
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
}
```

**Comment by johanneswuerbach** [comment]
What is the error log you are seeing?

**Comment by tylerball** [comment]
Similar to @BernsteinA's. Here's the output:

```
❯ testem ci                                                                                                                                                                                          10:59am
not ok 1 testem - testem
    ---
        message: >
            Error: Non-zero exit code: 1
            Hook: before_tests
            Stdout:

            Usage: npm <command>

            where <command> is one of:
                access, add-user, adduser, apihelp, author, bin, bugs, c,
                cache, completion, config, ddp, dedupe, deprecate, dist-tag,
                dist-tags, docs, edit, explore, faq, find, find-dupes, get,
                help, help-search, home, i, info, init, install,
                install-test, issues, it, la, link, list, ll, ln, login,
                logout, ls, outdated, owner, pack, ping, prefix, prune,
                publish, r, rb, rebuild, remove, repo, restart, rm, root,
                run-script, s, se, search, set, show, shrinkwrap, star,
                stars, start, stop, t, tag, team, test, tst, un, uninstall,
                unlink, unpublish, unstar, up, update, upgrade, v, verison,
                version, view, whoami

            npm <cmd> -h     quick help on <cmd>
            npm -l           display full usage info
            npm faq          commonly asked questions
            npm help <term>  search for help on <term>
            npm help npm     involved overview

            Specify configs in the ini-formatted file:
                /Users/tball/.npmrc
            or on the command line via: npm <command> --key value
            Config info can be viewed via: npm help config

            npm@3.6.0 /Users/tball/.nvm/versions/node/v5.7.0/lib/node_modules/npm

            Stderr:

    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
```
