### ISSUE TITLE
Retry mechanism?

### ISSUE THREAD

**Issue by patocallaghan** [testem/testem#1015]
Hey, 

we get the below error quite a lot of times in our CI environment which causes our tests to fail/timeout. From looking at the Testem documentation it doesn't appear that Testem has retry functionality but do you know of a strategy which could detect this error and then retry the tests? 

```
not ok 1 Browser "google-chrome --user-data-dir=/tmp/testem-2441 --no-default-browser-check --no-first-run --ignore-certificate-errors --test-type --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:7357/2441/tests/index.html?hidepassed&filter=team%20observe%20%7C" failed to connect. testem.js not loaded?
```

**Comment by stripedpumpkin** [comment]
Same problem here in CI (Codeship) running `COVERAGE=true nvm exec ./node_modules/ember-cli/bin/ember test`.
We run our ember tests with phantom first and then with chrome

**testem.js**
```
/*jshint node:true*/
module.exports = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS",
    "Chrome"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
};
```


**log**
```
[... 1288 ok tests with phantom ...]
Error: request aborted
at IncomingMessage.onAborted (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/raw-body/index.js:269:10)
at emitNone (events.js:86:13)
at IncomingMessage.emit (events.js:185:7)
at abortIncoming (_http_server.js:283:11)
at Socket.serverSocketCloseListener (_http_server.js:296:5)
at emitOne (events.js:101:20)
at Socket.emit (events.js:188:7)
at TCP._handle.close [as _onclose] (net.js:498:12)
not ok 1289 Browser "google-chrome --user-data-dir=/tmp/testem-949 --no-default-browser-check --no-first-run --ignore-certificate-errors --test-type --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:7357/949/tests/index.html?hidepassed" failed to connect. testem.js not loaded?

1..1289
# tests 1289
# pass  1288
# skip  0
# fail  1
Not all tests passed.
Error: Not all tests passed.
at EventEmitter.getExitCode (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/lib/app.js:434:15)
at EventEmitter.exit (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/lib/app.js:189:23)
at /home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/lib/app.js:103:14
at tryCatcher (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/node_modules/bluebird/js/release/promise.js:510:31)
at Promise._settlePromise (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/node_modules/bluebird/js/release/promise.js:567:18)
at Promise._settlePromise0 (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/node_modules/bluebird/js/release/promise.js:612:10)
at Promise._settlePromises (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/node_modules/bluebird/js/release/promise.js:691:18)
at Async._drainQueue (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/node_modules/bluebird/js/release/async.js:138:16)
at Async._drainQueues (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues (/home/rof/src/bitbucket.org/myuser/myapp/frontend/node_modules/testem/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:637:20)
at tryOnImmediate (timers.js:610:5)
at processImmediate [as _immediateCallback] (timers.js:582:5)
```
Tends to happen 1 out of 4 times. Rest of the time, tests are running with chrome.

**Comment by johanneswuerbach** [comment]
Testem has no build-in functionality for retrying lunchers today, but PRs are more then welcome.
