### ISSUE TITLE
RangeError: out of range index

### ISSUE THREAD

**Issue by Turbo87** [testem/testem#1026]
I've started seeing the following error lately when running `ember test`, which is using `testem` underneath:

```
/Users/tbn/Code/ember-test-helpers/node_modules/ws-pure/lib/Receiver.js:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (/Users/tbn/Code/ember-test-helpers/node_modules/ws-pure/lib/Receiver.js:386:24)
    at Receiver.add (/Users/tbn/Code/ember-test-helpers/node_modules/ws-pure/lib/Receiver.js:86:3)
    at Socket.realHandler (/Users/tbn/Code/ember-test-helpers/node_modules/ws-pure/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

I can't reliably reproduce it, but it's currently triggering every two/three times when I run `ember test` in that repository.

`ws-pure` is apparently used by `socket.io-pure`, which is used by `testem`. Since those two libs seems to be forks of the original libraries I've chosen to open the issue here.

**Comment by johanneswuerbach** [comment]
Which version of testem are you running? Newer versions are using the default socket.io as all native dependencies have been removed.

**Comment by Turbo87** [comment]
This seems to be using v0.9.11 of testem. Good point about the version numbers... I'll try to upgrade and see if that helps 👍

**Comment by Turbo87** [comment]
this seems to have been resolved by updating, thanks!
