### ISSUE TITLE
Examples won't run locally as commander is not installed

### ISSUE THREAD

**Issue by callmemagnus** [testem/testem#1085]
I tried the 2 following examples:

1. coverage_istanbul
2. tape_example

Both of them are failing, on `npm test`  with the following error:
```
> @ pretest /home/magnus/src/products/testem/examples/coverage_istanbul
> rimraf coverage instrumented coverage*.json


> @ test /home/magnus/src/products/testem/examples/coverage_istanbul
> node ../../testem.js ci -P 10

module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/magnus/src/products/testem/testem.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Test failed.  See above for more details.
```

I am using: 
```
$ uname -a
Linux work-1604 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ node --version
v6.9.5
$ npm --version
4.4.1
```

I tried to just add `commander` to the project dependencies but it does not work.

Is `commander` required to be install globally ?

**Comment by johanneswuerbach** [comment]
`commander` is a testem dependency, how did you install testem? https://github.com/testem/testem/blob/53c2c520a08f10e8f15771087797de6f7be11ff2/package.json#L27

**Comment by johanneswuerbach** [comment]
If you just clone this repository and execute the scripts, you would also need to run `npm install` in the main project folder.

**Comment by callmemagnus** [comment]
Ok, that worked. It probably makes sense.

I didn't noticed: `node ../../testem.js ci -P 10`.

Sorry for the noise.
