### ISSUE TITLE
Test failure details are not printed to console using TAP and testem ci

### ISSUE THREAD

**Issue by kmoe** [testem/testem#1172]
I noticed this bug in a project that uses `testem`, `qunitjs`, and `qunit-tap` - it's possible that the issue is in another of these dependencies, or that I have misunderstood TAP. However, I was able to reproduce what seems like a failing test case using examples in this repo. I have also forked this repo to produce a failing test case that more accurately reflects my project.

## Case 1

**Steps to reproduce**
1. Check out this repo and go to `examples/node_tap_example`.
2. Modify `hello.js` or `tests.js` so at the first test fails.
3. run `npm install` and `npm test`.

**Actual results**
```
❤ @glit ➜  node_tap_example git:(qunit-tap-example) ★ npm test

> @ test /home/katy/dev/tallarium/testem/examples/node_tap_example
> node ../../testem.js ci -P 10 --launch tap

not ok 1 tap - it says hello world
ok 2 tap - it says hello to person

1..2
# tests 2
# pass  1
# skip  0
# fail  1
```

**Expected results**
I would expect to see the reason for failure, or a stack trace, underneath the line beginning `not ok`.

For this example I was not able to find where the stack trace 'went' - logging the `stack` at this point https://github.com/testem/testem/blob/bb5d517ce8dc30a911dd266978af57517d4fe328/lib/tap_consumer.js#L53 
yields only the first line of the stack trace.

## Case 2

**Steps to reproduce**
1. Check out https://github.com/kmoe/testem/tree/qunit-tap-example and go to `examples/qunit_tap`.
2. Run `npm install` and `npm test` (we expect both tests to fail).

**Actual results**
```
❤ @glit ➜  qunit_tap git:(qunit-tap-example) ★ npm test

> @ test /home/katy/dev/tallarium/testem/examples/qunit_tap
> node ../../testem.js ci

not ok 1 Node - Died on test #1     at Object.<anonymous> (/home/katy/dev/tallarium/testem/examples/qunit_tap/tests.js:12:7)
not ok 2 Node - Died on test #1     at Object.<anonymous> (/home/katy/dev/tallarium/testem/examples/qunit_tap/tests.js:16:7)

1..2
# tests 2
# pass  0
# skip  0
# fail  2
npm ERR! Test failed.  See above for more details.

```
Note that in this case the reason for test failure is in the test name for some reason.

**Expected results**
By logging data from the `comment` event on the TAP stream in `tap_consumer.js`, we get a bit more information:
```
❤ @glit ➜  qunit_tap git:(qunit-tap-example) ★ npm test

> @ test /home/katy/dev/tallarium/testem/examples/qunit_tap
> node ../../testem.js ci

# module: hello

# test: says hello world

not ok 1 Node - Died on test #1     at Object.<anonymous> (/home/katy/dev/tallarium/testem/examples/qunit_tap/tests.js:12:7)
#     at Module._compile (module.js:571:32)

#     at Object.Module._extensions..js (module.js:580:10)

#     at Module.load (module.js:488:32)

#     at tryModuleLoad (module.js:447:12)

#     at Function.Module._load (module.js:439:3)

#     at Module.runMain (module.js:605:10): Error, expected: null, got: null, test: says hello world, module: hello, source: at failEveryTime (/home/katy/dev/tallarium/testem/examples/qunit_tap/hello.js:7:11)

#     at hello (/home/katy/dev/tallarium/testem/examples/qunit_tap/hello.js:2:5)

#     at Object.<anonymous> (/home/katy/dev/tallarium/testem/examples/qunit_tap/tests.js:13:18)

# test: says hello to person

not ok 2 Node - Died on test #1     at Object.<anonymous> (/home/katy/dev/tallarium/testem/examples/qunit_tap/tests.js:16:7)
#     at Module._compile (module.js:571:32)

#     at Object.Module._extensions..js (module.js:580:10)

#     at Module.load (module.js:488:32)

#     at tryModuleLoad (module.js:447:12)

#     at Function.Module._load (module.js:439:3)

#     at Module.runMain (module.js:605:10): Error, expected: null, got: null, test: says hello to person, module: hello, source: at failEveryTime (/home/katy/dev/tallarium/testem/examples/qunit_tap/hello.js:7:11)

#     at hello (/home/katy/dev/tallarium/testem/examples/qunit_tap/hello.js:2:5)

#     at Object.<anonymous> (/home/katy/dev/tallarium/testem/examples/qunit_tap/tests.js:17:18)

# failed 2 of 2 tests


1..2
# tests 2
# pass  0
# skip  0
# fail  2
```

## Fix

I am happy to submit a PR to fix this behaviour, as currently this issue means whenever I see a test fail through `testem` on my project I must rerun the tests without testem in order to see why they failed.

However, it seems that there may be some inconsistency in the way that diagnostic information is reported through TAP, so I would appreciate advice from maintainers as to what the correct way to populate test failure reason and stack trace is.

**Comment by ControlTheBit** [comment]
+1
