### ISSUE TITLE
Possibly nest teamcity suites by launcher

### ISSUE THREAD

**Issue by makepanic** [testem/testem#1187]
Hi,
the teamcity spec allows to [nest test suites](https://confluence.jetbrains.com/display/TCD65/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingTests):

```
##teamcity[testSuiteStarted name='suite.name']
##teamcity[testSuiteStarted name='nested.suite']
##teamcity[testStarted name='package_or_namespace.ClassName.TestName']
##teamcity[testFailed name='package_or_namespace.ClassName.TestName' message='The number should be 20000' details='junit.framework.AssertionFailedError: expected:<20000> but was:<10000>|n|r    at junit.framework.Assert.fail(Assert.java:47)|n|r    at junit.framework.Assert.failNotEquals(Assert.java:280)|n|r...']
##teamcity[testFinished name='package_or_namespace.ClassName.TestName']
##teamcity[testSuiteFinished name='nested.suite']
##teamcity[testSuiteFinished name='suite.name']
```

The current implementation only emits a flat list of test results. 
I'm unsure if we could nest the output because this requires the reporter to wait for all tests inside a launcher to be finished.

Nested output allows an easier navigation through test results. See for example:

![20171021-121058](https://user-images.githubusercontent.com/1205444/31879677-6b7e0f78-b7de-11e7-884b-2e017ddb82d1.png)

Which is nested by grouping the results by their first `/(.*) - /` match.

**Comment by stefanpenner** [comment]
> Nested output allows an easier navigation through test results. See for example:

that does look better. Any interest in pursuing this?

**Comment by makepanic** [comment]
Sure. 
I'll write some tests and create a PR.
