### ISSUE TITLE
Trunk is red due to issue with an electron integration test

### ISSUE THREAD

**Issue by stefanpenner** [testem/testem#1350]
Trunk is red due to issue with an electron integration test

for example:
```
not ok 1 cli - [undefined ms] - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Non-zero exit code: 1
            Stderr: 
             /home/travis/build/testem/testem/examples/electron/runtests.js:48
                throw error;
                ^
            
            Error: Command failed: /home/travis/build/testem/testem/examples/electron/node_modules/electron/dist/electron file:///tmp/tmp-11555cfkLtiMnP3wk.html?testemId=204898281410
            /home/travis/build/testem/testem/examples/electron/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
            
                at ChildProcess.exithandler (child_process.js:294:12)
                at ChildProcess.emit (events.js:198:13)
                at maybeClose (internal/child_process.js:982:16)
                at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
            
            
        browser log: |
            [object Object]
            [object Object]
            [object Object]
```

**Comment by stefanpenner** [comment]
@astronomersiva fixed this for us.
