### ISSUE TITLE
Trunk is red due to issue with saucelabs

### ISSUE THREAD

**Issue by stefanpenner** [testem/testem#1352]
https://travis-ci.org/testem/testem/jobs/557407168

```
not ok 3 SL_Chrome_Current_No_Details - [undefined ms] - bailout
    ---
        message: >
            Error: [init({"browserName":"chrome","deviceName":"","deviceOrientation":"","tags":["Saucie","test"],"name":"Saucie tests","public":"public","build":"3418","tunnelIdentifier":"3418.5","version":"latest","platform":"Windows 10"})] The environment you requested was unavailable.
    ...
not ok 4 SL_Chrome_Current - [undefined ms] - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Stderr: 
             { Error: [init({"browserName":"chrome","deviceName":"","deviceOrientation":"","tags":["Saucie","test"],"name":"Saucie tests","public":"public","build":"3418","tunnelIdentifier":"3418.5","version":"latest","platform":"Windows 10"})] The environment you requested was unavailable.
            Sauce could not start your job. For more information on what happened, please visit https://app.saucelabs.com/tests/d4e749d8da274d5db32712b9f4285233
                at /home/travis/build/testem/testem/node_modules/wd/lib/webdriver.js:140:15
                at Request._callback (/home/travis/build/testem/testem/node_modules/wd/lib/http-utils.js:89:7)
                at Request.self.callback (/home/travis/build/testem/testem/node_modules/wd/node_modules/request/request.js:186:22)
                at emitTwo (events.js:126:13)
                at Request.emit (events.js:214:7)
                at Request.<anonymous> (/home/travis/build/testem/testem/node_modules/wd/node_modules/request/request.js:1163:10)
                at emitOne (events.js:116:13)
                at Request.emit (events.js:211:7)
                at IncomingMessage.<anonymous> (/home/travis/build/testem/testem/node_modules/wd/node_modules/request/request.js:1085:12)
                at Object.onceWrapper (events.js:313:30)
                at emitNone (events.js:111:20)
                at IncomingMessage.emit (events.js:208:7)
                at endReadableNT (_stream_readable.js:1064:12)
                at _combinedTickCallback (internal/process/next_tick.js:139:11)
                at process._tickCallback (internal/process/next_tick.js:181:9)
              cause: 
               { Error: [init({"browserName":"chrome","deviceName":"","deviceOrientation":"","tags":["Saucie","test"],"name":"Saucie tests","public":"public","build":"3418","tunnelIdentifier":"3418.5","version":"latest","platform":"Windows 10"})] The environment you requested was unavailable.
            Sauce could not start your job. For more information on what happened, please visit https://app.saucelabs.com/tests/d4e749d8da274d5db32712b9f4285233
                at /home/travis/build/testem/testem/node_modules/wd/lib/webdriver.js:140:15
                at Request._callback (/home/travis/build/testem/testem/node_modules/wd/lib/http-utils.js:89:7)
                at Request.self.callback (/home/travis/build/testem/testem/node_modules/wd/node_modules/request/request.js:186:22)
                at emitTwo (events.js:126:13)
                at Request.emit (events.js:214:7)
                at Request.<anonymous> (/home/travis/build/testem/testem/node_modules/wd/node_modules/request/request.js:1163:10)
                at emitOne (events.js:116:13)
                at Request.emit (events.js:211:7)
                at IncomingMessage.<anonymous> (/home/travis/build/testem/testem/node_modules/wd/node_modules/request/request.js:1085:12)
                at Object.onceWrapper (events.js:313:30)
                at emitNone (events.js:111:20)
                at IncomingMessage.emit (events.js:208:7)
                at endReadableNT (_stream_readable.js:1064:12)
                at _combinedTickCallback (internal/process/next_tick.js:139:11)
                at process._tickCallback (internal/process/next_tick.js:181:9)
                 data: '{"status": 13, "sessionId": "d4e749d8da274d5db32712b9f4285233", "value": {"message": "Sauce could not start your job. For more information on what happened, please visit https://app.saucelabs.com/tests/d4e749d8da274d5db32712b9f4285233"}}' },
              isOperational: true,
              data: '{"status": 13, "sessionId": "d4e749d8da274d5db32712b9f4285233", "value": {"message": "Sauce could not start your job. For more information on what happened, please visit https://app.saucelabs.com/tests/d4e749d8da274d5db32712b9f4285233"}}' }
            
            Stdout: 
             Bail out! Error: [init({"browserName":"chrome","deviceName":"","deviceOrientation":"","tags":["Saucie","test"],"name":"Saucie tests","public":"public","build":"3418","tunnelIdentifier":"3418.5","version":"latest","platform":"Windows 10"})] The environment you requested was unavailable.
            Sauce could not start your job. For more information on what happened, please visit https://app.saucelabs.com/tests/d4e749d8da274d5db32712b9f4285233
            
            
        browser log: |
            [object Object]
            [object Object]
            [object Object]
    ...
```

**Comment by stefanpenner** [comment]
cc @astronomersiva

**Comment by rwjblue** [comment]
> Trunk

```
         ___     _,.--.,_
      .-~   ~--"~-.   ._ "-.
     /      ./_    Y    "-. \
    Y       :~     !         Y
    lq p    |     /         .|
 _   \. .-, l    /          |j
()\___) |/   \_/";          !
 \._____.-~\  .  ~\.      ./
            Y_ Y_. "vr"~  T
            (  (    |L    j   -Row
            [nn[nn..][nn..]
        ~~~~~~~~~~~~~~~~~~~~~~~
```

😛

**Comment by astronomersiva** [comment]
@stefanpenner, this seems to be related to some SauceLabs setting. I think the best course of action here would be check any relevant settings in SauceLabs or contact their support.

**Comment by stefanpenner** [comment]
Good idea. I’ll try and poke around this weekend

**Comment by stefanpenner** [comment]
@step2yeung I have no had a chance, if you could reach out that would be awesome.

**Comment by stefanpenner** [comment]
Thank you!
