### ISSUE TITLE
Example custom reporter not working

### ISSUE THREAD

**Issue by amk221** [testem/testem#906]
I'm trying to use the _example custom reporter_ with an ember app.
It runs fine, but then afterwards outputs an error about `getExitCode`

steps to recreate:
1. `ember new example`
2. `ember generate component x-foo`
3. make test fail
4. _add testem's example [custom test reporter](https://github.com/testem/testem/blob/master/docs/custom_reporter.md)_
5. `ember test`

```
PhantomJS 2.1   ok  JSHint | app.js: should pass jshint
PhantomJS 2.1   ok  JSHint | components/x-foo.js: should pass jshint
PhantomJS 2.1   ok  JSHint | helpers/destroy-app.js: should pass jshint
PhantomJS 2.1   ok  JSHint | helpers/module-for-acceptance.js: should pass jshint
PhantomJS 2.1   ok  JSHint | helpers/resolver.js: should pass jshint
PhantomJS 2.1   ok  JSHint | helpers/start-app.js: should pass jshint
PhantomJS 2.1   failed  Integration | Component | x foo: it renders
PhantomJS 2.1   ok  JSHint | integration/components/x-foo-test.js: should pass jshint
PhantomJS 2.1   ok  JSHint | resolver.js: should pass jshint
PhantomJS 2.1   ok  JSHint | router.js: should pass jshint
PhantomJS 2.1   ok  JSHint | test-helper.js: should pass jshint
undefined/11 tests passed
Not all tests passed.
Error: Not all tests passed.
    at EventEmitter.App.getExitCode (/Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/lib/app.js:384:14)
    at EventEmitter.<anonymous> (/Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/lib/app.js:197:39)
    at /Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:726:13
    at /Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:52:16
    at /Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:269:32
    at /Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:44:16
    at /Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:723:17
    at /Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:167:37
    at EventEmitter.App.removeSignalListeners (/Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/lib/app.js:413:5)
    at /Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:718:13
    at iterate (/Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:262:13)
    at /Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:274:29
    at /Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:44:16
    at Server.<anonymous> (/Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:723:17)
    at Server.<anonymous> (/Users/andrew/Desktop/example/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:167:37)
    at Server.g (events.js:286:16)
```

**Comment by johanneswuerbach** [comment]
Looks like you are using the broken testem `v1.9.0` release, could you check whether `v1.9.1` fixes your issue?

**Comment by amk221** [comment]
ah. Still happens I'm afraid

**Comment by webark** [comment]
ya.. same thing here.

```ok 13 PhantomJS 2.1 - JSHint | test-helper.js: should pass jshint

1..13
# tests 13
# pass  12
# skip  0
# fail  1
Not all tests passed.
Error: Not all tests passed.
    at EventEmitter.App.getExitCode (/Users/mavery/Documents/OSS/ember-component-css/node_modules/ember-cli/node_modules/testem/lib/app.js:384:14)
```

**Comment by webark** [comment]
looks like for me I tracked this down to something in ember-cli ... It looks like testem raises an `new Error` https://github.com/testem/testem/blob/master/lib/app.js#L397 and that error has a `.stack` property, then get's caught by
```CLI.prototype.logError = function(error) {
  if (this.testing && error) {
    console.error(error.message);
    if (error.stack) {
      console.error(error.stack);
    }
    throw error;
  }
  this.ui.errorLog.push(error);
  this.ui.writeError(error);
  return 1;
};```
in ember cli. `this.testing` is undefined.. which not sure what that is supposed to be..
but the `this.ui.writeError` has
```  if (error.stack) {
    ui.writeLine(error.stack, 'ERROR');
  }
```
and since `new Error` has a `.stack` property.. it dumps that out there.

**Comment by webark** [comment]
I guess you could do something like..
```javascript
    if (this.reporter.total > ((this.reporter.pass || 0) + (this.reporter.skipped || 0))) {
      var _error = new Error('Not all tests passed.');
      _error.stack = undefined;
      return _error;
    }
```
cause will you ever want a stack trace for just the fact that all tests aren't passing?

**Comment by amk221** [comment]
Just wondering if I could get an official update on this one? Thank you!

**Comment by amk221** [comment]
Anybody?

**Comment by johanneswuerbach** [comment]
Sorry, I didn't had time to look into this. Could you share some of the custom reporter code you are trying to get running?

**Comment by amk221** [comment]
I'm using the example custom reporter
https://github.com/testem/testem/blob/master/docs/custom_reporter.md

**Comment by rafalik2pl** [comment]
I have same isssue, any solutions?

**Comment by webark** [comment]
@rafalik2pl you should upgrade to the latest beta version. _(need to get this on the readme)_

**Comment by amk221** [comment]
Wondering... if this is 'just a docs thing' could you let us know what we need to do in order to get this to work? :)

**Comment by amk221** [comment]
...dreams of one day running a custom test reporter...

**Comment by johanneswuerbach** [comment]
https://github.com/ember-cli/ember-cli/pull/6385 together with https://github.com/testem/testem/pull/1001 should fix this behaviour. Would be glad when somebody could confirm that.
