### ISSUE TITLE
Testem crashes with no errors

### ISSUE THREAD

**Issue by robguy21** [testem/testem#928]
So the following file seems to be crashing testem. As soon as it's loaded up my testem crashes in the terminal but no error messages are being displayed.

This is the file:

```
import React from 'react';

const { string } = React.PropTypes;

const Todo = ({ text }) => (
  <li>
    {text}
  </li>
);

Todo.propTypes = {
  text: string,
};


export default Todo;
```

It looks as if it's crashing on another ReactJS component I've written in a similar fashion as the above.

Any idea's or suggestions on how to go about debugging this?

My system:

OSX El Capitan 10.11.5
testem version 1.1.0.0-1
node version v5.7.0

**Comment by cades** [comment]
Unknown Crash +1, on `v1.10.0` and `v1.10.1`.

`testem` will fireup UI and immediately quit
`testem ci` will run normally.

**Comment by robguy21** [comment]
When running ci mode with only chrome enabled the following error is displayed:

```
Invariant Violation: Could not find "store" in either the context or props of "Connect(Counter)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Counter)".
```

I was going to comment to say that this seems to be an error on my side... but in my browser my app is running fine, not sure why when run with testem my store isn't passed down the chain but in my real app, when run through the browser, it is.

**Comment by NicolasPelletier** [comment]
I got the same behavior as @cades.

Here is an extract ( I removed the middle bit ) of the log when I ran with '--debug':
```
info Test'em starting..
info Seeking for config file...
info Starting dev
info Starting server
info node
info runnerAdded
info runnerAdded
info Start triggered test run.
info Running tests...
info node onStart
info cmd: mocha -R tap
info executing: mocha -R tap
info spawning: phantomjs - [ '/Users/pelletn/lagoa_src/LynxCollaborationServer/node_modules/testem/assets/phantom.js',
  'http://localhost:7357/1912' ]
info New client connected: PhantomJS 2.1 1912
info tryAttach PhantomJS 2.1 1912
info PhantomJS 2.1 onStart
info Browser PhantomJS finished all tests. undefined
info PhantomJS 2.1 onEnd

.. Lots of 'File changed: ... triggered test run' ...
info Running tests...
.. Lots of 'File changed: ... triggered test run' ...
info Running tests...
info Running tests...
info Running tests...
info Running tests...
info Running tests...

info ok 1 Test API endpoints accessible by the server Check the occupancy of humans in a given room

info ok 2 Test API endpoints accessible by the server Check the occupancy of androids in a given room

info ok 3 Test API endpoints accessible by the server Check the occupancy of robots in a given room

info ok 4 Test API endpoints accessible by the server Check the total occupancy of collaborators in a given room

info ok 5 Test API endpoints accessible by the server Check the occupancy of a non-existent room

info ok 6 Test API endpoints accessible by the server Check the occupancy of an unknown collaborator type

info ok 7 Node specific tests should pass

WARN node closed null
info Process node terminated. null 'SIGTERM'
info Process node terminated. null 'SIGTERM'
WARN PhantomJS closed 1
info Process PhantomJS terminated. 1 null
```

I have testem 1.10.1
Mac OSX 10.11.6
NodeJS 4.4.7

**Comment by NicolasPelletier** [comment]
I tried with Node 6.3.1 just for fun and got a different set of events. Here they are:
```
info Test'em starting.. 
info Seeking for config file... 
info Starting dev 
info Starting server 
info node 
info runnerAdded 
info runnerAdded 
info Start triggered test run. 
info Running tests... 
info node onStart
info cmd: mocha -R tap 
info executing: mocha -R tap 
info spawning: phantomjs - [ '/Users/pelletn/lagoa_src/LynxCollaborationServer/node_modules/testem/assets/phantom.js',
  'http://localhost:7357/2145' ] 
info ok 1 Test API endpoints accessible by the server Check the occupancy of humans in a given room
 
info ok 2 Test API endpoints accessible by the server Check the occupancy of androids in a given room
 
info ok 3 Test API endpoints accessible by the server Check the occupancy of robots in a given room
 
info ok 4 Test API endpoints accessible by the server Check the total occupancy of collaborators in a given room
 
info ok 5 Test API endpoints accessible by the server Check the occupancy of a non-existent room
 
info ok 6 Test API endpoints accessible by the server Check the occupancy of an unknown collaborator type
 
info ok 7 Node specific tests should pass
 
WARN node closed 0
info node onEnd
info New client connected: PhantomJS 2.1 2145 
info tryAttach PhantomJS 2.1 2145
info PhantomJS 2.1 onStart
info Browser PhantomJS finished all tests. undefined
info PhantomJS 2.1 onEnd
info PhantomJS 2.1 onEnd
info Browser PhantomJS finished all tests. undefined
info PhantomJS 2.1 onEnd
info PhantomJS 2.1 onEnd
info Browser PhantomJS finished all tests. undefined
info PhantomJS 2.1 onEnd
info PhantomJS 2.1 onEnd
info Browser PhantomJS finished all tests. undefined
info PhantomJS 2.1 onEnd
info PhantomJS 2.1 onEnd

... A few 'File changed: ... triggered test run'

info Process node already killed. 
info Running tests... 
info Running tests... 
info Running tests... 
info Process node already killed. 
WARN PhantomJS closed 1
info Process PhantomJS terminated. 1 null
```

As you can see, in this case PhantomJS ran second. Don't know if that makes a difference, but I thought I'd mention it.

**Comment by NicolasPelletier** [comment]
I reverted back to 1.9.1 and everything runs as expected.

**Comment by robguy21** [comment]
Did another thing, running in normal mode testem closes unexpectedly, running with ci mode i get the expected error

```
not ok 1 PhantomJS - PhantomJS
    ---
        message: >
            Stderr:
             module.js:341
                throw err;
                ^

            Error: Cannot find module 'redux-mock-store'
                at Function.Module._resolveFilename (module.js:339:15)
                at Function.Module._load (module.js:290:25)
                at Module.require (module.js:367:17)
                at require (internal/module.js:16:19)
                at Object.<anonymous> (App.spec.js:4:1)
                at Module._compile (module.js:413:34)
                at loader (/Users/robguy21/dev/robguy21/my-project/node_modules/babel-register/lib/node.js:158:5)
                at Object.require.extensions.(anonymous function) [as .js] (/Users/robguy21/dev/robguy21/my-project/node_modules/babel-register/lib/node.js:168:7)
                at Module.load (module.js:357:32)
                at Function.Module._load (module.js:314:12)


        Log: |
...
```

my testem.log

```
info Test'em starting.. 
info Seeking for config file... 
info Starting ci 
info Starting server 
info Start triggered test run. 
info Running tests... 
info cmd: babel-tape-runner ./src/assets/js/**/*.spec.js 
info executing: babel-tape-runner ./src/assets/js/**/*.spec.js 
WARN PhantomJS closed 1
info Process PhantomJS already killed. 
```

Getting the exact same behaviour in 1.9.1

Work around of the crashing is to `P`ause right as tests begin. This will display errors without crashing the testem process. This is a bit of an inconvenience though, I think the work-around to this might be the option-- `bail_on_uncaught_error` which defaults to true... but when I add it to my config and run testem the same behaviour happens.

....After going about my business the following error appeared in the header of testem terminal view:
```
(node) warning: possible EventEmitter memory leak detected. 11 processError listeners added. Use emitter.setMaxListeners() to increase limit.
```

**Comment by johanneswuerbach** [comment]
Release in `1.10.2`
