### ISSUE TITLE
Test timed out

### ISSUE THREAD

**Issue by andrei-sheina** [testem/testem#986]
I have an Ember app and using standard ember testing configuration (testem, phantom, qunit). I am trying to launch the simplest test, here is the code:
```
import Ember from "ember";
import { module, test } from 'qunit';
import startApp from '../helpers/start-app';
var App;

module('An Integration test', {
  beforeEach: function() {
    App = startApp();
  },
  afterEach: function() {
    Ember.run(App, App.destroy);
  }
});

test("Page contents", function(assert) {
  visit('/sign-in')
  .then(function() {
    assert.equal(Ember.$('div.brand').length, 1, "I am on sign in page");
    fillIn('input#login', 'blabla@mail.com');
    fillIn('input#password', 'qwerty');
    click('button.btn')
    .then(() => {
      assert.equal(Ember.$('li.breadcrumb-item:contains("Weekly Imports")').length, 1, "I am on weekly imports page");
    })
  });
});
```

And i'm getting the following error in terminal:
```
not ok 1 PhantomJS 2.1 - An Integration test: Page contents
    ---
        actual: >
            null
        message: >
            Test timed out
        Log: |
    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
Not all tests passed.
Error: Not all tests passed.
    at EventEmitter.App.getExitCode (/home/andrei/Work/front-end-logstics/node_modules/testem/lib/app.js:434:15)
    at EventEmitter.App.exit (/home/andrei/Work/front-end-logstics/node_modules/testem/lib/app.js:189:23)
    at /home/andrei/Work/front-end-logstics/node_modules/testem/lib/app.js:103:14
    at tryCatcher (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/andrei/Work/front-end-logstics/node_modules/testem/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
Obviously problem with promises (simple test without using promises works fine).
How can i fix that?

**Comment by johanneswuerbach** [comment]
Not really sure how ember tests work, but looks like you missed a `return visit('/sign-in')` to return the promise.

Otherwise a better place might be the ember-cli issue page.
